### PR TITLE
Upgraded core build gradle to .kts

### PR DESCRIPTION
**Pull request by Reedyuk**
Minor change, moved build gradle over to a .kts one instead of the groovy one.

### CODE REVIEW

**Comment by wenxi-zeng** [comment]
we will have to change all other gradle files to .kts too. however, .kts follows a strict structure in order to recognize other .kts files. we will have to build a plugin to fully transform from groovy. I'd suggest to put this on hold until after GA

**Comment by Reedyuk** [comment]
GA?

**Comment by wenxi-zeng** [comment]
> GA?

general availability. we'll soon be on that phase

**Comment by prayansh** [comment]
@Reedyuk thanks for this upgrade ❤️ . We are currently working on our big release so might be a bit delayed on this change / response.

**Pull request closed without merging**
